---
title: "Recognition Plots"
author: "Gözem Turan"
date: "29 6 2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(lme4) 
library(car)
library(tidyr)
library(Rmisc)
library(rstatix)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(ez)
library(psycho)
library(sjPlot)
library(PupillometryR)
library(MetBrewer)
library(here)
library(styler)
library(readr)
```

# Open data seperately
```{r}
# set root path where the project file is
root_path <- here::here()  
### Path variables ----
data_path <- file.path(root_path, "data")


exp1_data_raw <- read_csv(file = file.path(data_path, "raw_data", "exp_1.csv"))
# original name: L:/2_Research/2_Analysis_Folder/MemVio//part3_RTout.csv"

exp2_data_raw <- read_csv(file = file.path(data_path, "raw_data", "exp_2.csv"))
# original name: L:/2_Research/2_Analysis_Folder/Wubbles//part3_RTout.csv

```

Preparations for exp1_data
```{r}
exp1_data <- exp1_data_raw %>%
  mutate(
    pe = factor(pe, 
                levels = c("lowPE", "medPE", "highPE", "new"),
                labels = c("low", "med", "high", "new")),
    participant = factor(participant),
    conf = factor(conf, levels = c("1", "2", "3", "4")),
    experiment = "1"
  ) %>%
  drop_na()

# exp1_data$pe <- factor(exp1_data$pe, levels = c("lowPE", "medPE", "highPE")) # pe
# 
# exp1_data$participant <- as.factor(exp1_data$participant) # participants
# 
# exp1_data$conf <- factor(exp1_data$conf, levels = c("1", "2", "3", "4")) # confidence
# 
# exp1_data <- na.omit(exp1_data)
# 
# exp1_data$study <- c("Experiment 1")

```

# preparations for exp2_data
```{r}

# change the naming for PE levels to be consistend
exp2_data <- exp2_data_raw %>%
  rename(pe = PE_level) %>%
  mutate(
    pe = factor(pe,
                levels = c("low", "medium", "high", "new"),
                labels = c("low", "med", "high", "new")),
    participant = factor(participant),
    conf = factor(conf, levels = c("1", "2", "3", "4")),
    experiment = "2"
  ) %>%
  drop_na()
  

# exp2_data$pe <- factor(exp2_data$PE_level, levels = c("lowPE", "medPE", "highPE")) # pe
# 
# exp2_data$participant <- as.factor(exp2_data$participant) # participants
# 
# exp2_data$conf <- factor(exp2_data$conf, levels = c("1", "2", "3", "4")) # confidence
# 
# exp2_data <- na.omit(exp2_data)
# 
# exp2_data$study <- c("Experiment 2")

```

# Combine two data sets
```{r}

full_data <- bind_rows(exp1_data, exp2_data)
# # just ignore the na values
# 
# full_data$study <- as.factor(full_data$study)

```

# New variable for plots
```{r}

plot_data <- full_data %>%
  select(participant, pe, corrAns, experiment)

```

# Aggregated data
```{r}

full_data1 <- summarySE(full_data, measurevar = "corrAns", groupvars = c("pe", "experiment"), na.rm = TRUE)

full_data11 <- summarySE(full_data,
  measurevar = "corrAns",
  groupvars = c("pe", "participant", "experiment"), na.rm = TRUE
)
```

# First plot - Rainyclouds
```{r}
ggplot(full_data11, aes(x = pe, y = corrAns, fill = pe)) +

  # distrubition
  geom_flat_violin(position = position_nudge(x = .1, y = 0), adjust = 1.5, trim = TRUE, color = "white") +
  # individual data points
  geom_point(aes(x = as.numeric(pe) - .15, y = corrAns), position = position_jitter(width = .05, height = 0), size = 1, shape = 20) +
  # box plot
  # geom_boxplot(aes(x = pe, y = corrAns),outlier.shape = NA, width = .1, colour = "black") +
  # instead of box plots, error bars
  geom_errorbar(data = full_data1, aes(ymin = corrAns - se, ymax = corrAns + se, width = 0.1)) +
  geom_point(data = full_data1, size = 1) +
  # group mean line
  geom_line(data = full_data1, aes(x = pe, y = corrAns), size = 0.5, group = 1) +

  # visual things
  theme_classic() +
  scale_fill_manual(values = met.brewer("Derain", 5, type = "continuous")) +
  scale_color_manual(values = met.brewer("Derain", 5, type = "continuous")) +
  scale_x_discrete(name = "PE Level", labels = c("lowPE" = "Low", "medPE" = "Medium", "highPE" = "High")) +
  theme(text = element_text(family = "TT Times New Roman", size = 15), legend.title = element_text(size = 1), legend.text = element_text(size = 12), legend.position = "None", legend.direction = "vertical") +
  ylab("Hit Responses") +
  ylim(0, 1) +

  # significance
  # geom_signif(comparisons = list(c("lowPE", "highPE")), map_signif_level=TRUE, y_position = c(1.1, 1.2, 1.3)) +

  # studies
  facet_wrap(. ~ study)

```

# Second plot - spaghetti & box & distribution
```{r}

rain_height <- .1

ggplot(full_data11, aes(x = 1, y = corrAns, fill = pe)) +

  # clouds
  geom_flat_violin(trim = TRUE, position = position_nudge(x = 2.3), alpha = .9, color = "black") +
  # rain
  geom_point(aes(x = factor(pe), y = corrAns, fill = factor(pe)), size = 2.5, shape = 21) +
  # spaghetti
  geom_line(aes(x = factor(pe), y = corrAns, group = participant)) +
  # box
  geom_boxplot(
    width = .1, show.legend = FALSE,
    outlier.shape = NA, alpha = .9,
    position = position_nudge(x = 2.2)
  ) +
  # group mean
  # geom_line(data=full_data1, aes(x=pe, y=corrAns), size=1.4, group=1, color = "pink") +

  # visual things
  scale_fill_manual(values = met.brewer("Derain", 5, type = "continuous")) +
  theme_classic() +
  scale_x_discrete(name = "PE Level", labels = c("lowPE" = "Low", "medPE" = "Medium", "highPE" = "High")) +
  theme(text = element_text(family = "TT Times New Roman", size = 15), legend.title = element_text(size = 1), legend.text = element_text(size = 12), legend.position = "None", legend.direction = "vertical") +
  ylab("Hit Responses") +
  ylim(0, 1) +

  # significance
  # geom_signif(comparisons = list(c("low", "dprimeMed"), c("dprimeLow", "dprimeHigh"), c("dprimeMed", "dprimeHigh")), map_signif_level=TRUE) +

  # studies
  facet_wrap(. ~ study)

```


# Third plot - violin
```{r}

ggplot(full_data11, aes(x = pe, y = corrAns, fill = pe)) +
  geom_violin(color = "white", trim = TRUE) +

  # subject lines
  geom_jitter(aes(x = pe, y = corrAns, group = participant, alpha = 0.5), color = "gray50", size = 0.5, position = position_dodge(0)) +
  geom_line(aes(x = pe, y = corrAns, group = participant, alpha = 0.5), color = "gray50", position = position_dodge(0)) +

  # group mean
  geom_point(data = full_data1, size = 1) +
  # error bar
  geom_errorbar(data = full_data1, aes(ymin = corrAns - se, ymax = corrAns + se, width = 0.1)) +
  geom_line(data = full_data1, aes(x = pe, y = corrAns), size = 0.9, group = 1) +

  # visual things
  scale_x_discrete(name = "PE Level", labels = c("lowPE" = "Low", "medPE" = "Medium", "highPE" = "High")) +
  scale_fill_manual(values = met.brewer("Derain", 5, type = "continuous")) +
  theme_classic() +
  theme(text = element_text(family = "TT Times New Roman", size = 15), legend.title = element_text(size = 1), legend.text = element_text(size = 12), legend.position = "None", legend.direction = "vertical") +
  ylab("Hit Responses") +
  # ylim(0, 1) +

  # significance
  geom_signif(comparisons = list(c("highPE", "lowPE")), map_signif_level = FALSE) +

  # studies
  facet_wrap(. ~ study)
  
```


# CONFINDENCE 
```{r}

full_data2 <- summarySE(full_data, measurevar = "corrAns", groupvars = c("pe", "study", "conf"), na.rm = TRUE)


full_data22 <- summarySE(full_data,
  measurevar = "corrAns",
  groupvars = c("pe", "participant", "conf", "study"), na.rm = TRUE
)

```

PLOT
```{r}

ggplot(full_data22, aes(x = pe, y = corrAns, fill = pe)) +
  geom_violin(color = "white", trim = TRUE) +

  # subject lines
  geom_jitter(aes(x = pe, y = corrAns, group = participant, alpha = 0.5), color = "gray50", size = 0.5, position = position_dodge(0)) +
  geom_line(aes(x = pe, y = corrAns, group = participant, alpha = 0.5), color = "gray50", position = position_dodge(0)) +

  # group mean
  geom_point(data = full_data2, size = 1) +
  # error bar
  geom_errorbar(data = full_data2, aes(ymin = corrAns - se, ymax = corrAns + se, width = 0.1)) +
  geom_line(data = full_data2, aes(x = pe, y = corrAns), size = 0.9, group = 1) +

  # visual things
  scale_x_discrete(name = "PE Level", labels = c("lowPE" = "Low", "medPE" = "Medium", "highPE" = "High")) +
  scale_fill_manual(values = met.brewer("Derain", 5, type = "continuous")) +
  theme_classic() +
  theme(text = element_text(family = "TT Times New Roman", size = 15), legend.title = element_text(size = 1), legend.text = element_text(size = 12), legend.position = "None", legend.direction = "vertical") +
  ylab("Hit Responses") +
  ylim(0, 1) +

  # significance
  # geom_signif(comparisons = list(c("low", "dprimeMed"), c("dprimeLow", "dprimeHigh"), c("dprimeMed", "dprimeHigh")), map_signif_level=TRUE) +

  # studies
  facet_grid(conf ~ study)
  
```
